apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garage-bootstrap.fullname" . }}-config
  labels:
    {{- include "garage-bootstrap.labels" . | nindent 4 }}
data:
  bootstrap-config.json: |
    {{ include "garage-bootstrap.config" . | nindent 4 }}
