{{- if and .Values.garage.adminToken (not .Values.garage.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage-bootstrap.fullname" . }}-admin-token
  labels:
    {{- include "garage-bootstrap.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.garage.adminToken | b64enc | quote }}
{{- end }}
