{{- if .Values.bootstrap.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "garage-bootstrap.serviceAccountName" . }}
  labels:
    {{- include "garage-bootstrap.labels" . | nindent 4 }}
  {{- with .Values.bootstrap.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
